#!/bin/bash

# Use awk to process the Apache log file, count occurrences, and sort
awk '{ip_code = $1 " " $9} {count[ip_code]++} END {for (ic in count) {print count[ic], ic}}' /var/log/apache2/access.log | sort -nr

