#!/usr/bin/env bash
# This Bash script get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it

sudo apt install apache2
echo 'Hello Holberton' > /var/www/index.html
sudo service apache2 restart